GET https://cdn.contentful.com/spaces/20wsojjwdirk/environments/master/entries/?select=fields.productName,fields.price,fields.productId,fields.productDescription&content_type=electricStoreItems
content-type: application/json
Authorization: Bearer AFcBSZYtr6KRHV1zcRGI7BIwUiCLrtEmjdYyQGDFHpU

###

GET https://cdn.contentful.com/spaces/20wsojjwdirk/environments/master/entries/
content-type: application/json
Authorization: Bearer AFcBSZYtr6KRHV1zcRGI7BIwUiCLrtEmjdYyQGDFHpU


###
GET https://cdn.contentful.com/spaces/20wsojjwdirk/environments/master/entries/4lQ4gexwgKw3qZq5b933Iw
content-type: application/json
Authorization: Bearer AFcBSZYtr6KRHV1zcRGI7BIwUiCLrtEmjdYyQGDFHpU


###
GET https://cdn.contentful.com/spaces/20wsojjwdirk/environments/master/assets/3pd0QxyjKqTkeLeO5lnnGF
content-type: application/json
Authorization: Bearer AFcBSZYtr6KRHV1zcRGI7BIwUiCLrtEmjdYyQGDFHpU


###
GET https://cdn.contentful.com/spaces/20wsojjwdirk/environments/master/entries/?select=fields.productCategory&content_type=electricStoreItems
content-type: application/json
Authorization: Bearer AFcBSZYtr6KRHV1zcRGI7BIwUiCLrtEmjdYyQGDFHpU


